--CAU1
DECLARE @TBTHONGKE TABLE (MAPB INT, LUONGTB FLOAT)

INSERT INTO @TBTHONGKE
	SELECT PHG, AVG(LUONG) FROM NHANVIEN GROUP BY PHG

SELECT TENNV, PHG, LUONG, LUONGTB,
TINHTRANG = CASE
WHEN LUONG > LUONGTB THEN 'KHONG TANG LUONG'
ELSE 'TANG LUONG'
END
	FROM NHANVIEN A
INNER JOIN @TBTHONGKE B
ON A.PHG = B.MAPB

--CHUC VU
DECLARE @TBTHONG TABLE (MAPB INT, LUONGTB FLOAT)

INSERT INTO @TBTHONG
	SELECT PHG, AVG(LUONG) FROM NHANVIEN GROUP BY PHG

SELECT TENNV, PHG, LUONG, LUONGTB,
CHUCVU = CASE
WHEN LUONG > LUONGTB THEN 'TRUONG PHONG'
ELSE 'NHAN VIEN'
END
	FROM NHANVIEN A
INNER JOIN @TBTHONG B
ON A.PHG = B.MAPB
--GIOI TINH
SELECT TENNV= CASE PHAI
WHEN 'NAM' THEN 'MR.' + TENNV
WHEN N'NỮ' THEN 'MS.' + TENNV
END
FROM NHANVIEN
--THUE
SELECT TENNV, LUONG, THUE = CASE
WHEN LUONG BETWEEN 0 AND 25000 THEN LUONG * 0.1
WHEN LUONG BETWEEN 25000 AND 30000 THEN LUONG * 0.12
WHEN LUONG BETWEEN 30000 AND 40000 THEN LUONG * 0.15
WHEN LUONG BETWEEN 40000 AND 50000 THEN LUONG * 0.2
ELSE LUONG * 0.25
END
FROM NHANVIEN
--CAU2
DECLARE @i INT = 2, @dem INT;
SET @dem = (SELECT COUNT(*) FROM NHANVIEN)
WHILE (@i < @dem)
BEGIN
	SELECT MANV, TENNV FROM NHANVIEN
	WHERE CAST(MANV AS INT) = @i;
	SET @i = @i + 2;
end
--bo so 4
DECLARE @a INT = 2, @dem2 INT;
SET @dem2 = (SELECT COUNT(*) FROM NHANVIEN)
WHILE (@a < @dem2)
BEGIN
IF (@a=4)
	BEGIN
		SET @a=@a+2
		CONTINUE;
	END
	SELECT MANV, TENNV FROM NHANVIEN
	WHERE CAST(MANV AS INT) = @a;
	SET @a = @a + 2;
end
--CAU3
BEGIN TRY
	INSERT PHONGBAN (TENPHG, MAPHG, TRPHG, NG_NHANCHUC)
	VALUES ('KE HOACH',111,'017','2020-12-12')
	PRINT 'CHEN THANH CONG'
END TRY
BEGIN CATCH
	PRINT 'THEM DU LIEU THAT BAI' + CONVERT(VARCHAR,  ERROR_NUMBER(),1)
	+ '=>' + ERROR_MESSAGE()
END CATCH

