--CÂU A
Create proc sp_Bai1_a @name nvarchar(20)
as
	begin 
		Print 'Xin chào: '+@name
	end
exec sp_Bai1_a 'Nhóm 11'
--CÂU B
Create proc sp_Bai1_b @numbera int, @numberb int
as 
	begin
		declare @sum int =0;
		set @sum= @numbera + @numberb
		print N'Tổng là:' + cast(@sum as varchar(10))
	end 

exec sp_Bai1_b 10,7
--CÂU C
Create proc sp_Bai1_c @n int, @i int 
as 
	begin
		declare @sum int = 0; 
		while @i < @n
			begin 
				set @sum= @sum + @i
				set @i=@i +2
			end
			print 'Tong so chan: '+ cast(@sum as varchar(10))
	end 

exec sp_Bai1_c 10
--CÂU D
Create proc sp_Bai1_d @a int, @b int 
as 
	begin
		while (@a !=@b)
		begin
			if (@a>@b)
				set @a = @a -@b
			else
				set @b= @b - @a
			end 
		return @a
end

Declare @c int
exec @c= sp_Bai1_d 15,20
print @c
--bai2
--BAI2_1
CREATE PROC BAI2_01 
@MANV VARCHAR(5)
AS
BEGIN
	SELECT * FROM NHANVIEN WHERE MANV=@MANV
END

EXEC BAI2_01 @MANV ='001'
--BAI2_2
SELECT COUNT(MANV),MADA, TENPHG FROM NHANVIEN
INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
INNER JOIN DEAN ON DEAN.PHONG=PHONGBAN.MAPHG
GROUP BY TENPHG,MADA

--BAI2_3
CREATE PROC BAI2_3 @MANV INT
AS
BEGIN
	SELECT COUNT(MANV) AS 'SO LUONG' , MADA,TENPHG FROM NHANVIEN
	INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
	INNER JOIN DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
	WHERE MADA = @MANV
	GROUP BY TENPHG, MADA
END
EXEC BAI2_3 1

--BAI2_4
CREATE PROC BAI2_4 @MATP INT
AS
BEGIN
SELECT HONV,TENNV,TENPHG,NHANVIEN.MANV, THANNHAN.* FROM NHANVIEN
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
LEFT OUTER JOIN THANNHAN ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
WHERE THANNHAN.MA_NVIEN IS NULL AND TRPHG = @MATP
END

EXEC BAI2_4 '008'

--BAI2_5
CREATE PROC BAI2_5 @MANV VARCHAR(5), @MAPB VARCHAR(5)
AS
BEGIN
	IF EXISTS (SELECT * FROM NHANVIEN WHERE MANV = @MANV AND PHG=@MAPB)
		PRINT 'NHAN VIEN: ' +@MANV+' CO TRONG PHONG BAN: ' +@MAPB
	ELSE
		PRINT 'NHAN VIEN: ' +@MANV+' KHONG CO TRONG PHONG BAN: ' +@MAPB
END

EXEC BAI2_5 '001','4'
---------
--CAU3
CREATE PROC THEMPHONGBANMOI @TENPHG NVARCHAR(20), @MAPHG INT, @TRPHG NVARCHAR(10), @NG_NHANCHUC DATE
AS
BEGIN
	IF EXISTS(SELECT * FROM PHONGBAN WHERE MAPHG = @MAPHG)
	BEGIN
		PRINT('MA PHONG BAN DA TON TAI');
		RETURN;
	END

INSERT INTO [DBO].[PHONGBAN]
	([TENPHG],[MAPHG],[TRPHG],[NG_NHANCHUC])
VALUES
	(@TENPHG, @MAPHG, @TRPHG, @NG_NHANCHUC)
END

EXEC THEMPHONGBANMOI 'IT',11,'005','2022-11-29'
--------------
CREATE PROC CAPNHATPHONGBAN
	@OLDTENPHG NVARCHAR(15),
	@TENPHG NVARCHAR(15),
	@MAPHG INT,
	@TRPHG NVARCHAR(10),
	@NG_NHANCHUC DATE
AS
BEGIN
	UPDATE [DBO].[PHONGBAN]
		SET
			[TENPHG]=@TENPHG, [MAPHG]=@MAPHG, [TRPHG]=@TRPHG, [NG_NHANCHUC]=@NG_NHANCHUC
		WHERE TENPHG=@OLDTENPHG;
	END;

EXEC [DBO].[CAPNHATPHONGBAN] 'CNTT','IT',10,'005','1-1-2020'
--------
CREATE PROC sp_insertNV @Ho NVARCHAR(15),@tenNV NVARCHAR(15),@MaNV NVARCHAR(9),
@NgaySinh DATETIME,@diachi NVARCHAR(30),@phai NVARCHAR(3),@luong FLOAT,@Ma_NQL NVARCHAR(9),@PHG INT
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM PHONGBAN WHERE TENPHG like 'IT')
	BEGIN
		PRINT 'NHAN VIEN phai la phong IT'
	RETURN
END
IF @luong < 25000
SET @Ma_NQL='009'
ELSE
BEGIN
SET @Ma_NQL = '005'
END
DECLARE @age INT = datediff(YEAR,@ngaySinh,getDate())
IF(@phai like 'nam' and @age > 65 and @age <18)
BEGIN
PRINT 'nam phai tu 18 - 65 '
RETURN
END
ELSE IF(@phai like N'Nữ' and @age > 60 and @age < 18)
BEGIN
PRINT 'nu phai tu 18-60'
RETURN
END
INSERT INTO NHANVIEN(HONV,TENLOT,TENNV,MANV,NGSINH,DCHI,PHAI,LUONG,MA_NQL,PHG)
VALUES(@Ho,@tenNV,@MaNV,@NgaySinh,@diachi,@phai,@luong,@Ma_NQL,@PHG)
END